name: Preview Deploy

on:
  workflow_dispatch:

jobs:
  build:
    name: Preview publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build --workspaces --if-present
      - name: Publish Calendar worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          workingDirectory: 'workers/calendar'
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: "publish --env preview"
