name: Pull Request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build --workspaces --if-present
      - name: Run validate
        run: npm run validate --workspaces --if-present
      - name: Run tests
        run: npm run test --workspaces --if-present -- --run
